### ISSUE TITLE
Recent Xbox Screenshots not showing

### ISSUE THREAD

**Issue by aaronbentley** [Strafer14/Xbox-Live-API---Node#4]
Hello, 

first off - thank you @Strafer14  for making an awesome lil' package, is a pleasure to work with.

I'm having an issue where a users recent screenshots aren't being included when I call `getScreenshotsForGamer`. 🤷‍♂️
The `getClipsForGamer` doesn't appear to suffer from the same issue as it always includes the most recent user clips.

Do you have any ideas as to why this is happening?

Thanks in advance,

Aaron.

**Comment by Strafer14** [comment]
Sorry for the long wait, can you give me an example of a user you expect to get screenshots (seeing screenshots on Xbox) but not being able to?
Also, can you elaborate? Are you getting an empty response or only part of the screenshots?

**Comment by Strafer14** [comment]
This should now be fixed, feel free reopening the issue if it still persists
