### ISSUE TITLE
Cannot find module './lib/api'

### ISSUE THREAD

**Issue by aaronbentley** [Strafer14/Xbox-Live-API---Node#6]
Hey,

I'm trying to run use this (latest version 3.0.1) within a Firebase Function, but I keep getting the following error:
```
FirebaseError: Failed to load function definition from source: Failed to generate manifest from function source: Error: Cannot find module './lib/api'
```

Any ideas why I'm getting this?

**Comment by Strafer14** [comment]
I made a mistake when uploading 3.0.1 and npmignored the lib folder which is necessary, this is now fixed, apologies.
