### ISSUE TITLE
Which api can get game play time

### ISSUE THREAD

**Issue by Asteroidxx** [Strafer14/Xbox-Live-API---Node#7]

**Comment by Strafer14** [comment]
This is the complete reference for all the URIs, currently, I support the ones that were useful for me on a different project (in which I used this library).
https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/reference/live/rest/uri/atoc-xboxlivews-reference-uris

For your convenience I've added the activity history endpoint I found to this library, it's not exactly what you've asked for as it only gives dates for in-game achievements.

Could you clarify - by game play time you want an aggregate of all the time a user played a certain game?
His latest gaming session time?
The timestamps(start time) of games he played?
